job/urls.py
from django.conf.urls import url

from . import views

app_name = "job"

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^service/$', views.one_service, name='one_service'),
    url(r'^service/profile$', views.profile, name='profile'),
]

services/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('job.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

job/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

# To use it at filter by ville
class Ville(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return str(self.name)

# Service means catecory of servivces : exemples electicite, plamberie ..
class Service(models.Model):
    name = models.CharField(max_length=20)
    icon = models.ImageField(upload_to='upload/')
    about = models.TextField()

    def __str__(self):
        return str(self.name)

# class Worker
class Worker(models.Model):
    cin = models.CharField(max_length=20)
    name = models.CharField(max_length=20)
    lastname = models.CharField(max_length=20)
    phone = models.CharField(max_length=20)
    email = models.EmailField()
    work = models.ForeignKey(Service, on_delete=models.CASCADE)
    city = models.ForeignKey(Ville, on_delete=models.CASCADE)
    img = models.ImageField(upload_to='upload/')

    def __str__(self):
        return str(self.cin)


#class Work mean contra beetwen client and Worker
class Work(models.Model):
    pass

job/views.py
from django.shortcuts import render
from .models import Service, Worker



# Create your views here.
def index(request):
    service = Service.objects.all()
    return render(request,'job/index.html', {'service' : service})


# View service onClick on img service new page render with filter service
# 2 optinel param city of woker on status (libre,oucuper)
def one_service(request, city=None, status=None):
    service = request.GET.get('service')
    workers = Worker.objects.all()
    return render(request,'job/finder.html',{'workers' : workers, 'service' : service})

def profile(request):
    idprofil = request.GET.get('profil')
    worker = Worker.objects.get(id=idprofil)
    return render(request, 'job/profile.html', {'worker' : worker})

job/templates/job/finder.html
{% load staticfiles %}
<!DOCTYPE HTML>

<html>
	<head>
		<title>Services</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
<link rel="shortcut icon" href="{% static 'job/assets/images/img.png' %}" />
		
		<link rel="stylesheet" type="text/css" href="{% static 'job/assets/css/main.css' %}" />

	</head>
	<body>
		<!-- Wrapper -->
			<div id="wrapper">

				<!-- Header -->
					<header id="header">
						<div class="inner">

							<!-- Logo -->
								<a href="{% url 'job:profile' %}" class="logo">
									<span class="symbol"><img src="{% static 'job/images/logo.svg' %}" alt="" /></span><span class="title">Services</span>
								</a>

							<!-- Nav -->
								<nav>
									<ul>
										<li><a href="#menu">Menu</a></li>
									</ul>
								</nav>

						</div>
					</header>

				<!-- Menu -->
					<nav id="menu">
						<h2>Menu</h2>
						<ul>
							<li><a href="{% url 'job:index' %}">Home</a></li>
							<li><a href="generic.html">Services</a></li>
							<li><a href="generic.html">Clients</a></li>
							<li><a href="generic.html">Sociéte</a></li>
							<li><a href="elements.html">Pack Complet</a></li>
							<li><a href="#" class="button special">Login/
								Sign Up</a></li>

						</ul>
					</nav>

				<!-- Main -->
					<div id="main">
						<div class="inner">
							<header>
								<h1>Nous Equipe</h1>
								<p>selectionner un de l equipe </p>
							</header>


							<section class="tiles">

								<!-- boucle for services -->
								{% for i in workers %}
								{% if i.work.name == service %}
								<article class="style1">
									<span class="image">
										<img src="{{ i.img.url }}" alt="" />
									</span>
									<a href="{% url 'job:profile' %}?profil={{i.id}}">
										<h2>{{ i.name }}</h2>
										<div class="content">
											<p>{{ i.phone }} <br> {{i.email}} </p>
										</div>
									</a>
								</article>
								{% endif %}
								{% endfor %}


							</section>
						</div>
					</div>

				<!-- Footer -->
					<footer id="footer">
						<div class="inner">
							<section>
								<h2>Get in touch</h2>
								<form method="post" action="#">
									<div class="field half first">
										<input type="text" name="name" id="name" placeholder="Name" />
									</div>
									<div class="field half">
										<input type="email" name="email" id="email" placeholder="Email" />
									</div>
									<div class="field">
										<textarea name="message" id="message" placeholder="Message"></textarea>
									</div>
									<ul class="actions">
										<li><input type="submit" value="Send" class="special" /></li>
									</ul>
								</form>
							</section>
							<section>
								<h2>Follow</h2>
								<ul class="icons">
									<li><a href="#" class="icon style2 fa-twitter"><span class="label">Twitter</span></a></li>
									<li><a href="#" class="icon style2 fa-facebook"><span class="label">Facebook</span></a></li>
									<li><a href="#" class="icon style2 fa-instagram"><span class="label">Instagram</span></a></li>
									<li><a href="#" class="icon style2 fa-dribbble"><span class="label">Dribbble</span></a></li>
									<li><a href="#" class="icon style2 fa-github"><span class="label">GitHub</span></a></li>
									<li><a href="#" class="icon style2 fa-500px"><span class="label">500px</span></a></li>
									<li><a href="#" class="icon style2 fa-phone"><span class="label">Phone</span></a></li>
									<li><a href="#" class="icon style2 fa-envelope-o"><span class="label">Email</span></a></li>
								</ul>
							</section>
							<ul class="copyright">
								<li>&copy; Untitled. All rights reserved</li><li>Developed: <a href="http://tik.tn">Tik Tn</a></li>
							</ul>
						</div>
					</footer>

			</div>

		<!-- Scripts -->

			<script src="{% static 'job/assets/js/jquery.min.js' %}"></script>
			<script src="{% static 'job/assets/js/skel.min.js' %}"></script>
			<script src="{% static 'job/assets/js/util.js' %}"></script>
			<script src="{% static 'job/assets/js/main.js' %}"></script>

	</body>
</html>

job/templates/job/generic.html
<!DOCTYPE HTML>
<!--
	Phantom by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
		<title>Generic - Phantom by HTML5 UP</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<!--[if lte IE 8]><script src="assets/js/ie/html5shiv.js"></script><![endif]-->
		<link rel="stylesheet" href="assets/css/main.css" />
		<!--[if lte IE 9]><link rel="stylesheet" href="assets/css/ie9.css" /><![endif]-->
		<!--[if lte IE 8]><link rel="stylesheet" href="assets/css/ie8.css" /><![endif]-->
	</head>
	<body>
		<!-- Wrapper -->
			<div id="wrapper">

				<!-- Header -->
					<header id="header">
						<div class="inner">

							<!-- Logo -->
								<a href="index.html" class="logo">
									<span class="symbol"><img src="images/logo.svg" alt="" /></span><span class="title">Phantom</span>
								</a>

							<!-- Nav -->
								<nav>
									<ul>
										<li><a href="#menu">Menu</a></li>
									</ul>
								</nav>

						</div>
					</header>

				<!-- Menu -->
					<nav id="menu">
						<h2>Menu</h2>
						<ul>
							<li><a href="index.html">Home</a></li>
							<li><a href="generic.html">Ipsum veroeros</a></li>
							<li><a href="generic.html">Tempus etiam</a></li>
							<li><a href="generic.html">Consequat dolor</a></li>
							<li><a href="elements.html">Elements</a></li>
						</ul>
					</nav>

				<!-- Main -->
					<div id="main">
						<div class="inner">
							<h1>Generic Page</h1>
							<span class="image main"><img src="images/pic13.jpg" alt="" /></span>
							<p>Donec eget ex magna. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque venenatis dolor imperdiet dolor mattis sagittis. Praesent rutrum sem diam, vitae egestas enim auctor sit amet. Pellentesque leo mauris, consectetur id ipsum sit amet, fergiat. Pellentesque in mi eu massa lacinia malesuada et a elit. Donec urna ex, lacinia in purus ac, pretium pulvinar mauris. Curabitur sapien risus, commodo eget turpis at, elementum convallis elit. Pellentesque enim turpis, hendrerit tristique.</p>
							<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis dapibus rutrum facilisis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam tristique libero eu nibh porttitor fermentum. Nullam venenatis erat id vehicula viverra. Nunc ultrices eros ut ultricies condimentum. Mauris risus lacus, blandit sit amet venenatis non, bibendum vitae dolor. Nunc lorem mauris, fringilla in aliquam at, euismod in lectus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In non lorem sit amet elit placerat maximus. Pellentesque aliquam maximus risus, vel venenatis mauris vehicula hendrerit.</p>
							<p>Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque venenatis dolor imperdiet dolor mattis sagittis. Praesent rutrum sem diam, vitae egestas enim auctor sit amet. Pellentesque leo mauris, consectetur id ipsum sit amet, fersapien risus, commodo eget turpis at, elementum convallis elit. Pellentesque enim turpis, hendrerit tristique lorem ipsum dolor.</p>
						</div>
					</div>

				<!-- Footer -->
					<footer id="footer">
						<div class="inner">
							<section>
								<h2>Get in touch</h2>
								<form method="post" action="#">
									<div class="field half first">
										<input type="text" name="name" id="name" placeholder="Name" />
									</div>
									<div class="field half">
										<input type="email" name="email" id="email" placeholder="Email" />
									</div>
									<div class="field">
										<textarea name="message" id="message" placeholder="Message"></textarea>
									</div>
									<ul class="actions">
										<li><input type="submit" value="Send" class="special" /></li>
									</ul>
								</form>
							</section>
							<section>
								<h2>Follow</h2>
								<ul class="icons">
									<li><a href="#" class="icon style2 fa-twitter"><span class="label">Twitter</span></a></li>
									<li><a href="#" class="icon style2 fa-facebook"><span class="label">Facebook</span></a></li>
									<li><a href="#" class="icon style2 fa-instagram"><span class="label">Instagram</span></a></li>
									<li><a href="#" class="icon style2 fa-dribbble"><span class="label">Dribbble</span></a></li>
									<li><a href="#" class="icon style2 fa-github"><span class="label">GitHub</span></a></li>
									<li><a href="#" class="icon style2 fa-500px"><span class="label">500px</span></a></li>
									<li><a href="#" class="icon style2 fa-phone"><span class="label">Phone</span></a></li>
									<li><a href="#" class="icon style2 fa-envelope-o"><span class="label">Email</span></a></li>
								</ul>
							</section>
							<ul class="copyright">
								<li>&copy; Untitled. All rights reserved</li><li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
							</ul>
						</div>
					</footer>

			</div>

		<!-- Scripts -->
			<script src="assets/js/jquery.min.js"></script>
			<script src="assets/js/skel.min.js"></script>
			<script src="assets/js/util.js"></script>
			<!--[if lte IE 8]><script src="assets/js/ie/respond.min.js"></script><![endif]-->
			<script src="assets/js/main.js"></script>

	</body>
</html>

job/templates/job/index.html
{% load staticfiles %}
<!DOCTYPE HTML>

<html>
<head>
    <title>Services</title>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <link rel="shortcut icon" href="{% static 'job/assets/images/img.png' %}"/>
    
    <link rel="stylesheet" type="text/css" href="{% static 'job/assets/css/main.css' %}"/>

</head>
<body>
<!-- Wrapper -->
<div id="wrapper">

    <!-- Header -->
    <header id="header">
        <div class="inner">

            <!-- Logo -->
            <a href="{% url 'job:index' %}" class="logo">
                <span class="symbol"><img src="{% static 'job/images/logo.svg' %}" alt=""/></span><span class="title">Services</span>
            </a>

            <!-- Nav -->
            <nav>
                <ul>
                    <li><a href="#menu">Menu</a></li>
                </ul>
            </nav>

        </div>
    </header>

    <!-- Menu -->
    <nav id="menu">
        <h2>Menu</h2>
        <ul>
            <li><a href="{% url 'job:index' %}">Home</a></li>
            <li><a href="generic.html">Services</a></li>
            <li><a href="generic.html">Clients</a></li>
            <li><a href="generic.html">Sociéte</a></li>
            <li><a href="elements.html">Pack Complet</a></li>
            <li><a href="#" class="button special">Login/
                Sign Up</a></li>

        </ul>
    </nav>

    <!-- Main -->
    <div id="main">
        <div class="inner">
            <header>
                <h1>Campus Services<br/>
                    Solution pour facilité votre vie.</h1>
                <p>Vous chercher un bonne ouvirier , vous avez un problem ou un panne urgent, ici la solution vite
                    choisir votre service et on 30 min notre agent va etre devent votre porte. </p>
            </header>


            <section class="tiles">

                <!-- boucle for services -->
                {% for i in service %}
                <article class="style1">
									<span class="image">
										<img src="{{ i.icon.url }}" alt=""/>
									</span>
                    <a href="{% url 'job:one_service' %}?service={{i.name}}">
                        <h2>{{ i.name }}</h2>
                        <div class="content">
                            <p>{{ i.about }}.</p>
                        </div>
                    </a>
                </article>
                {% endfor %}


            </section>
        </div>
    </div>

    <!-- Footer -->
    <footer id="footer">
        <div class="inner">
            <section>
                <h2>Get in touch</h2>
                <form method="post" action="#">
                    <div class="field half first">
                        <input type="text" name="name" id="name" placeholder="Name"/>
                    </div>
                    <div class="field half">
                        <input type="email" name="email" id="email" placeholder="Email"/>
                    </div>
                    <div class="field">
                        <textarea name="message" id="message" placeholder="Message"></textarea>
                    </div>
                    <ul class="actions">
                        <li><input type="submit" value="Send" class="special"/></li>
                    </ul>
                </form>
            </section>
            <section>
                <h2>Follow</h2>
                <ul class="icons">
                    <li><a href="#" class="icon style2 fa-twitter"><span class="label">Twitter</span></a></li>
                    <li><a href="#" class="icon style2 fa-facebook"><span class="label">Facebook</span></a></li>
                    <li><a href="#" class="icon style2 fa-instagram"><span class="label">Instagram</span></a></li>
                    <li><a href="#" class="icon style2 fa-dribbble"><span class="label">Dribbble</span></a></li>
                    <li><a href="#" class="icon style2 fa-github"><span class="label">GitHub</span></a></li>
                    <li><a href="#" class="icon style2 fa-500px"><span class="label">500px</span></a></li>
                    <li><a href="#" class="icon style2 fa-phone"><span class="label">Phone</span></a></li>
                    <li><a href="#" class="icon style2 fa-envelope-o"><span class="label">Email</span></a></li>
                </ul>
            </section>
            <ul class="copyright">
                <li>&copy; Untitled. All rights reserved</li>
                <li>Developed: <a href="http://tik.tn">Tik Tn</a></li>
            </ul>
        </div>
    </footer>

</div>

<!-- Scripts -->

<script src="{% static 'job/assets/js/jquery.min.js' %}"></script>
<script src="{% static 'job/assets/js/skel.min.js' %}"></script>
<script src="{% static 'job/assets/js/util.js' %}"></script>
<script src="{% static 'job/assets/js/main.js' %}"></script>

</body>
</html>

job/templates/job/profile.html
{% load staticfiles %}
<!DOCTYPE HTML>

<html>
<head>
    <title>Services</title>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <link rel="shortcut icon" href="{% static 'job/assets/images/img.png' %}"/>
    
    <link rel="stylesheet" type="text/css" href="{% static 'job/assets/css/main.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'job/assets/css/profile.css' %}"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

</head>

<body>
<!-- Wrapper -->
<div id="wrapper">

    <!-- Header -->
    <header id="header">
        <div class="inner">

            <!-- Logo -->
            <a href="{% url 'job:index' %}" class="logo">
                <span class="symbol"><img src="{% static 'job/images/logo.svg' %}" alt=""/></span><span class="title">Services</span>
            </a>

            <!-- Nav -->
            <nav>
                <ul>
                    <li><a href="#menu">Menu</a></li>
                </ul>
            </nav>

        </div>
    </header>

    <!-- Menu -->
    <nav id="menu">
        <h2>Menu</h2>
        <ul>
            <li><a href="{% url 'job:index' %}">Home</a></li>
            <li><a href="generic.html">Services</a></li>
            <li><a href="generic.html">Clients</a></li>
            <li><a href="generic.html">Sociéte</a></li>
            <li><a href="elements.html">Pack Complet</a></li>
            <li><a href="#" class="button special">Login/
                Sign Up</a></li>

        </ul>
    </nav>

    <!-- Main -->
    <div id="main">
        <div class="inner">
            <header>
                <h1>Campus Services<br/>
                    Solution pour facilité votre vie.</h1>
                <p>Vous chercher un bonne ouvirier , vous avez un problem ou un panne urgent, ici la solution vite
                    choisir votre service et on 30 min notre agent va etre devent votre porte. </p>
            </header>


            <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
            <div class="container">


                <h2 style="text-align:center">Worker {{worker.id}}</h2>

                <div class="card">
                    <img src="{{ worker.img.url }}" alt="John" style="width:50%">
                    <h1> {{worker.name}} {{worker.lastname}}</h1>
                    <p class="title">{{worker.email}}</p>
                    <p>{{worker.phone}}</p>
                    <p>{{worker.city}}</p>

                    <p>
                        <button>Contact</button>
                    </p>
                </div>


            </div>


        </div>

        <!-- Scripts -->

        <script src="{% static 'job/assets/js/jquery.min.js' %}"></script>
        <script src="{% static 'job/assets/js/skel.min.js' %}"></script>
        <script src="{% static 'job/assets/js/util.js' %}"></script>
        <script src="{% static 'job/assets/js/main.js' %}"></script>

</body>
</html>